### ISSUE TITLE
[url] tag only works when links have http:// prefixed

### ISSUE THREAD

**Issue by r04r** [r04r/Minichan#21]
It should default to http:// when this is missing.

**Comment by r04r** [comment]
Apparently `<a>` tags also require http:// so simply adjusting the validator to let them through won't do. Probably will have to make a custom code CodeDefinition?

**Comment by mpsmc** [comment]
Should this bug be raised against jBBCode? Would it be worth patching jBBCode?

**Comment by r04r** [comment]
I'm not quite sure. Technically URLs lacking the http:// are not valid, which is why the validator (which defers to php's FILTER_VALIDATE_URL) does not accept it. So the URL would need to be preprocessed somewhere, and their [DefaultCodeDefinitionSet](https://github.com/r04r/Minichan/blob/master/includes/formatters/1/JBBCode/DefaultCodeDefinitionSet.php) does not contain any extended CodeDefinitions so I'm not really sure if this would be all that appropiate. I also don't know how/if there are any other methods to handle this.

I've opened an issue on their issue tracker, but for now I'm thinking an independent fix on our side would be easiest. If my interpretation is correct then it could be mostly copy-pasted into the JBBCode library anyway.
