### ISSUE TITLE
Previewing a poll post causes poll options > 10 to be lost

### ISSUE THREAD

**Issue by mpsmc** [r04r/Minichan#22]
When creating a poll with more than 10 options, hitting preview, or encountering a validation error (such as 'body too short') causes the list of options to be truncated to the first 10 items.

To reproduce, create a new topic, enter some body text, enter options 1-11, hit preview, and then hit post.

Instead of the full list of options being available, only 10 are shown when viewing the preview.

(As an aside, it would also be nice if tabbing through the poll options placed the focus on the next input field. This does not happen for options > 3.)

**Comment by r04r** [comment]
Fixed by 60620559e9258ed853b86a8aea20de97da6db545
