### ISSUE TITLE
Unwanted scrolling in reply headers on mobile. (MC mobile allows you to shake people violently)

### ISSUE THREAD

**Issue by mpsmc** [r04r/Minichan#41]
When scrolling the page on a mobile, the page scrolling is interrupted by scrolling within the header of the reply.
No scrolling should happen inside the header of replies.
See a user report here https://minichan.org/topic/55099 for an alternative perspective.

**Comment by mpsmc** [comment]
Sounds like the CSS was required for cites and quotes.
https://minichan.org/topic/55327

**Comment by r04r** [comment]
That seems to have been a separate issue where webpack enabled strict mode for javascript, which some of the ancient functions did not like. Fixed in 74bd8cd47a2df661cd92412fca62711ea2ec419a and f6398f4a13ae2d5a5aaed066d27d5364f6a3e1a2
