### ISSUE TITLE
JavaScript deprecation warning when using Markup Editor buttons.

### ISSUE THREAD

**Issue by mpsmc** [r04r/Minichan#43]
A deprecation warning appears in Chrome's console tab when using the markup editor buttons.

1. Visit https://minichan.org/new_topic in Chrome
2. Open the JavaScript debug console.
3. Press the button labelled '[b]'.

The following deprecation warning is shown:
> A DOM event generated from JavaScript has triggered a default action inside the browser. This behavior is non-standard and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5718803933560832 for more details.

Removing the following code loses the warning.
```
	var event = document.createEvent('TextEvent');
	if(typeof event.initTextEvent == 'function') {
		event.initTextEvent('textInput', true, true, null, replacement);
		textArea.get(0).dispatchEvent(event);
	}else{
```

What does the above code do and is it important? The warning suggests it may not work for much longer.

**Comment by r04r** [comment]
No idea. Removed.
